---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  labels:
    managed: ""
    owner: ""
  name: nicnetworkconfigs.multitenancy.acn.azure.com
spec:
  group: multitenancy.acn.azure.com
  names:
    kind: NICNetworkConfig
    listKind: NICNetworkConfigList
    plural: nicnetworkconfigs
    shortNames:
    - nnc
    singular: nicnetworkconfig
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.nicID
      name: NICID
      type: string
    - jsonPath: .spec.ncID
      name: NCID
      type: string
    - jsonPath: .status.status
      name: Status
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NICNetworkConfig is the Schema for the nicnetworkconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: NICNetworkConfigSpec defines the desired state of NICNetworkConfig
            properties:
              nodeName:
                description: NodeName is the name of the Kubernetes node
                type: string
              podAllocations:
                description: PodAllocations tracks which pods are allocated on this
                  NIC
                items:
                  description: PodAllocation represents a pod's IP allocation on this
                    NIC
                  properties:
                    mtpnc:
                      description: MTPNC is the name of the MultitenantPodNetworkConfig
                      type: string
                    podName:
                      description: PodName is the name of the pod
                      type: string
                    podNamespace:
                      description: PodNamespace is the namespace of the pod
                      type: string
                  required:
                  - mtpnc
                  - podName
                  - podNamespace
                  type: object
                type: array
              podNetwork:
                description: PodNetwork is the name of the pod network
                type: string
              vnetID:
                description: VNetID is the Azure Virtual Network ID
                type: string
            required:
            - nodeName
            - podNetwork
            - vnetID
            type: object
          status:
            description: NICNetworkConfigStatus defines the observed state of NICNetworkConfig
            properties:
              accelnetEnabled:
                description: AccelnetEnabled determines if the CNI will provision
                  the NIC with accelerated networking enabled
                type: boolean
              availableIPs:
                description: AvailableIPs tracks the available IP addresses in this
                  NC block
                items:
                  type: string
                type: array
              deviceType:
                description: DeviceType is the device type that this NC was created
                  for
                enum:
                - acn.azure.com/vnet-nic
                - acn.azure.com/infiniband-nic
                type: string
              errorMessage:
                description: ErrorMessage contains error details if status is Error
                type: string
              gatewayIP:
                description: GatewayIP is the gateway ip of the injected subnet
                type: string
              macAddress:
                description: MacAddress is the MAC Address of the VM's NIC
                type: string
              ncID:
                description: NCID is the network container id created for this NIC
                type: string
              podAllocations:
                additionalProperties:
                  description: PodAllocation represents a pod's IP allocation on this
                    NIC
                  properties:
                    allocatedIP:
                      description: AllocatedIP is the IP address allocated to the
                        pod
                      type: string
                    mtpnc:
                      description: MTPNC is the name of the MultitenantPodNetworkConfig
                      type: string
                    podName:
                      description: PodName is the name of the pod
                      type: string
                    podNamespace:
                      description: PodNamespace is the namespace of the pod
                      type: string
                  required:
                  - allocatedIP
                  - mtpnc
                  - podName
                  - podNamespace
                  type: object
                description: PodAllocations tracks the allocated IP addresses to pod
                  mapping.
                type: object
              primaryIP:
                description: PrimaryIP is the primary IP allocated to the network
                  container
                type: string
              status:
                description: Status indicates the current status of the NIC Network
                  Config
                enum:
                - Ready
                - Pending
                - Error
                type: string
              subnetAddressSpace:
                description: SubnetAddressSpace is the subnet address space of the
                  injected subnet
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
